### ISSUE TITLE
不知道大佬有没有兴趣写一个私服联ban信息处理系统呀

### ISSUE THREAD

**Issue by wawcff** [mygoare/bf1#1]
那个生成器真的好棒啊 好方便啊

现在战地1贴吧社区有一个自发组织的 私服联ban 组织

目前加盟服务器：CDN、FATE、TNT、SAK、1975、HS、XJBD、CNA/H、KOI等

**原因：**大家写联ban名单都在 网易云笔记写 有时候更新可能不够规范 查询也比较困难= =

**构想：**

不知道大佬有没有兴趣做一个 挂壁ID及证据 玩家举报录入、管理录入、管理审核、挂壁名单公布的系统。。。

目前的构想是 每个加盟服务器 有一个 管理员账号可以管理系统的名单

然后 有新挂壁ID（可以玩家举报也可以管理员添加）在总名单的时候 这个私服管理员（比如KOI）的账号 可以对已手工加入游戏内本服务器ban list的ID进行标记 不要重复添加，对于未加、待加的有一个单独的名单，方便管理。

**玩家举报录入板块**：有ID、作弊方法、使用兵种、时间、地图模式、击杀数、B站视频证据地址（选填）

**大佬如果有兴趣的话可以加入联ban审查处呀527565465**

**我这里有一台NAS可以提供稳定的PHP MYSQL空间**

**Comment by mygoare** [comment]
666， 居然这么快就有人能找到这里来

可以的，没问题
